server:
  name: XNET
  host: 0.0.0.0
  shutdownTimeout: 5s

monitoring:
  ui: 
    container:
      elasticsearch:
        enabled: true

elasticsearch:
  hosts: 
    - https://es01:9200

#xpack:
#  fleet:
#    agentIdVerificationEnabled: false
